import { Obligation, Disbursement } from '@routes/ledger/ledger';

export const obligations: Obligation[] = [
	{
		id: '1',
		name: 'Sarah Wanjiru',
		category: 'family',
		amountDue: 450000,
		dueDate: '2023-10-24',
		status: 'overdue',
	},
	{
		id: '2',
		name: 'Jared Maina',
		category: 'friend',
		amountDue: 125750,
		dueDate: '2023-06-20',
		status: 'pending',
	},
	{
		id: '3',
		name: 'Emmanuel Otieno',
		category: 'shopkeeper',
		amountDue: 89000,
		dueDate: '2023-01-06',
		status: 'pending',
	},
	{
		id: '4',
		name: 'Catherine Njeri',
		category: 'colleague',
		amountDue: 12500,
		dueDate: '2023-12-16',
		status: 'pending',
	},
];

export const disbursements: Disbursement[] = [
	{
		id: 'KBU-0012',
		borrower: 'Jared Maina',
		initials: 'JM',
		principle: 15500,
		amountPaid: 0,
		dueDate: '2023-10-24',
		status: 'Unpaid',
		actionLabel: 'Nudge',
	},
	{
		id: 'KBU-0045',
		borrower: 'Sarah Wanjiru',
		initials: 'SW',
		principle: 8200,
		amountPaid: 8200,
		dueDate: '2023-10-28',
		status: 'Pending Verification',
		actionLabel: 'Verify Payment',
	},
	{
		id: 'KBU-0102',
		borrower: 'Emmanuel Otieno',
		initials: 'EO',
		principle: 22000,
		amountPaid: 10000,
		dueDate: '2023-10-15',
		status: 'Partially paid',
		actionLabel: 'Nudge',
	},
	{
		id: 'KBU-0125',
		borrower: 'Alice Musyoka',
		initials: 'AM',
		principle: 12000,
		amountPaid: 0,
		dueDate: '2023-11-02',
		status: 'Unpaid',
		actionLabel: 'Nudge',
	},
	{
		id: 'KBU-0089',
		borrower: 'John Njau',
		initials: 'JN',
		principle: 5500,
		amountPaid: 2500,
		dueDate: '2023-10-30',
		status: 'Partially paid',
		actionLabel: 'Nudge',
	},
	{
		id: 'KBU-0114',
		borrower: 'Lydia Kamau',
		initials: 'LK',
		principle: 18900,
		amountPaid: 18900,
		dueDate: '2023-11-05',
		status: 'Pending Verification',
		actionLabel: 'Verify Payment',
	},
	{
		id: 'KBU-0965',
		borrower: 'Leon Kamau',
		initials: 'LK',
		principle: 1467,
		amountPaid: 1467,
		dueDate: '2023-11-05',
		status: 'Pending Verification',
		actionLabel: 'Verify Payment',
	},
	{
		id: 'KBU-0584',
		borrower: 'Lydia Kamau',
		initials: 'LK',
		principle: 14560,
		amountPaid: 14560,
		dueDate: '2023-11-05',
		status: 'Pending Verification',
		actionLabel: 'Verify Payment',
	},
];
