import { Obligation, Disbursement } from '@routes/ledger/ledger';

export const obligations: Obligation[] = [
	{
		id: '1',
		name: 'Sarah Wanjiru',
		category: 'family',
		amountDue: 450000,
		dueDate: '2023-10-24',
		status: 'overdue',
	},
	{
		id: '2',
		name: 'Jared Maina',
		category: 'friend',
		amountDue: 125750,
		dueDate: '2023-06-20',
		status: 'pending',
	},
	{
		id: '3',
		name: 'Emmanuel Otieno',
		category: 'shopkeeper',
		amountDue: 89000,
		dueDate: '2023-01-06',
		status: 'pending',
	},
	{
		id: '4',
		name: 'Catherine Njeri',
		category: 'colleague',
		amountDue: 12500,
		dueDate: '2023-12-16',
		status: 'pending',
	},
];

export const disbursements: Disbursement[] = [
	{
		id: 'KBU-0012',
		borrower: 'Jared Maina',
		initials: 'JM',
		amount: 15500.0,
		dueDate: '2023-10-24',
		status: 'Active',
		actionLabel: 'Nudge',
	},
	{
		id: 'KBU-0045',
		borrower: 'Sarah Wanjiru',
		initials: 'SW',
		amount: 8200.0,
		dueDate: '2023-10-28',
		status: 'Pending Verification',
		actionLabel: 'Verify Payment',
	},
	{
		id: 'KBU-0102',
		borrower: 'Emmanuel Otieno',
		initials: 'EO',
		amount: 22000.0,
		dueDate: '2023-10-15',
		status: 'Paused',
		actionLabel: 'Nudge',
	},
	{
		id: 'KBU-0125',
		borrower: 'Alice Musyoka',
		initials: 'AM',
		amount: 12000.0,
		dueDate: '2023-11-02',
		status: 'Active',
		actionLabel: 'Nudge',
	},
	{
		id: 'KBU-0089',
		borrower: 'John Njau',
		initials: 'JN',
		amount: 5500.0,
		dueDate: '2023-10-30',
		status: 'Paused',
		actionLabel: 'Nudge',
	},
	{
		id: 'KBU-0114',
		borrower: 'Lydia Kamau',
		initials: 'LK',
		amount: 18900.0,
		dueDate: '2023-11-05',
		status: 'Pending Verification',
		actionLabel: 'Verify Payment',
	},
	{
		id: 'KBU-0965',
		borrower: 'Leon Kamau',
		initials: 'LK',
		amount: 1467.0,
		dueDate: '2023-11-05',
		status: 'Pending Verification',
		actionLabel: 'Verify Payment',
	},
	{
		id: 'KBU-0584',
		borrower: 'Lydia Kamau',
		initials: 'LK',
		amount: 14560.0,
		dueDate: '2023-11-05',
		status: 'Pending Verification',
		actionLabel: 'Verify Payment',
	},
];
